spring:
  application:
    # 注册时使用的服务名
    name: cloud-eureka

# eureka 服务器端口号
server:
  port: 8001

eureka:
  instance:
    # 注册的主机
    hostname: localhost
  client:
    # 是否将自己注册  在集群时打开
    registerWithEureka: false
    # 是否被检索 因为是单机版eureka 没必要检索
    fetchRegistry: false
    serviceUrl:
      # 服务注册url
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除
    enable-self-preservation: false